// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config"; // Pastikan impor dari @prisma/config

export default defineConfig({
  schema: "./prisma/schema.prisma", // Gunakan ./
  // migrations: {
  //   path: "./prisma/migrations",
  // },
  datasource: {
    // variabel ini wajib benar-benar ada di .env
    // Digunakan untuk operasional (lewat pooler)
    url: process.env.DATABASE_URL,
    // Menggunakan Supabase dengan directUrl:
    // Prisma 7 memerlukan directUrl didefinisikan secara eksplisit di sini jika menggunakan pooling
    // KHUSUS digunakan Prisma untuk migrasi (Direct ke port 5432)
    //directUrl: process.env.DIRECT_URL, 
    // mengbah sementara menjadi DIRECT_URL agar migrasi lancar
    // url: process.env.DIRECT_URL, 
    // directUrl: process.env.DIRECT_URL,
  },
});